# Generated by Django 4.1.2 on 2023-11-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0028_alter_personas_telefonomovil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='file',
            field=models.FileField(default=None, upload_to='mesagge/multimedia/'),
            preserve_default=False,
        ),
    ]
