# Generated by Django 4.1.2 on 2023-11-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0031_paises_alter_personas_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paises',
            options={'verbose_name': 'paise', 'verbose_name_plural': 'paises'},
        ),
        migrations.AlterModelTable(
            name='paises',
            table='paises',
        ),
    ]
