# Generated by Django 4.1.2 on 2023-11-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0032_alter_paises_options_alter_paises_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paises',
            options={'verbose_name': 'pais', 'verbose_name_plural': 'paises'},
        ),
        migrations.AddField(
            model_name='paises',
            name='codigo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
