# Generated by Django 4.1.2 on 2023-11-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0033_alter_paises_options_paises_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='grupo',
            field=models.IntegerField(null=True),
        ),
    ]
