# Generated by Django 4.1.2 on 2023-11-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0035_areas_grupos_secciones_gruposdestinatarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatarios',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grupo_destinatarios_persona', to='mensajeria.grupos', unique=True),
        ),
        migrations.AddField(
            model_name='destinatarios',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seccion_destinatarios_persona', to='mensajeria.secciones', unique=True),
        ),
    ]
