# Generated by Django 4.1.2 on 2023-11-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0037_alter_archivos_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='preview',
            field=models.TextField(blank=True),
        ),
    ]
