# Generated by Django 4.1.2 on 2023-12-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0038_archivos_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatarios',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grupo_destinatarios_persona', to='mensajeria.grupos'),
        ),
        migrations.AlterField(
            model_name='destinatarios',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seccion_destinatarios_persona', to='mensajeria.secciones'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='observaciones',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
