# Generated by Django 4.1.2 on 2023-12-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0039_alter_destinatarios_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones_area', to='mensajeria.areas'),
        ),
    ]
