# Generated by Django 4.1.2 on 2023-12-27 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajeria', '0045_archivos_weight_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatariosgrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatariosgrupos_created_by', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatariosGrupos_destinatarios', to='mensajeria.destinatarios')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatariosgrupos_grupos', to='mensajeria.grupos')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatariosgrupos_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'destinatariosgrupos',
                'verbose_name_plural': 'destinatariosgrupos',
                'db_table': 'destinatariosgrupos',
            },
        ),
        migrations.AlterField(
            model_name='personas',
            name='identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Identificacion'),
        ),
    ]
