name: CD
on:
  workflow_dispatch: 
  # push:
  #   branches: main
jobs:
  createcd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

  build:
    environment: dev
    runs-on: ubuntu-latest
    needs: createcd
    env:
      USERNAME: ubuntu
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            whoami
            cd main/
            git add .
            git commit -m"."
            git pull
            /home/ubuntu/.local/share/virtualenvs/main-zjSx5a4N/bin/supervisorctl restart todo-django
